kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-github
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
  username: R2FicmllbGVsb2dpdXJhdG8=
  password: Z2hwX0xabnl0c005N1JNUVhYTEV5VkhvMU5DbkFlaWc4MDNuM2s2OA==
type: kubernetes.io/basic-auth
---
kind: Secret
apiVersion: v1
metadata:
  name: html-openshift-app-generic-webhook-secret
  labels:
    app: html-openshift-app
    app.kubernetes.io/part-of: html-openshift-app
data:
 WebHookSecretKey: Mzg5YWU2MmZiZWRlZWQwZA==
type: Opaque